server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm index.php;

    location / {
        # CORRECCIÓN: Si el archivo no existe, permite buscar un index.php antes de ir a index.html
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        # Asegura que si el archivo PHP no existe físicamente, devuelva un error 404 de inmediato
        try_files $uri =404;
        
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
